---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups: ["cache.redhat.com"]
  resources: ["memcacheds"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["cache.redhat.com"]
  resources: ["memcacheds/finalizers"]
  verbs: ["update"]
- apiGroups: ["cache.redhat.com"]
  resources: ["memcacheds/status"]
  verbs: ["get", "patch", "update"]
